# Generated by Django 5.1.3 on 2024-11-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
